pull_request_rules:

  - name: Auto merge updating release pull request
    conditions:
      - and:
        - label=release
        - label!=conflicts
        - title~=Update release \(\d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash
